### ISSUE TITLE
React gives Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by octylFractal** [plantain-00/select2-component#46]
#### Code(if relevant):

```typescript
// given:
selected: string | undefined;
data: Select2Data;
setSelected: (selected: string) => void;

// then:
<Select2
        data={data}
        value={selected}
        update={(v): void => setSelected(v as string)}
    />
```

#### Expected:
Functioning component

#### Actual:
```
Error: Unable to find node on an unmounted component.
    at findHostInstanceWithWarning (webpack-internal:///./node_modules/.pnpm/react-dom@16.14.0_react@16.14.0/node_modules/react-dom/cjs/react-dom.development.js:24281:19)
    at Object.findDOMNode (webpack-internal:///./node_modules/.pnpm/react-dom@16.14.0_react@16.14.0/node_modules/react-dom/cjs/react-dom.development.js:24804:12)
    at Select2.componentDidMount (webpack-internal:///./node_modules/.pnpm/select2-react-component@5.10.4/node_modules/select2-react-component/dist/select2.js:124:65)
    at commitLifeCycles (webpack-internal:///./node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:20658:24)
    at commitLayoutEffects (webpack-internal:///./node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:23421:7)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at commitRootImpl (webpack-internal:///./node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:23146:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/.pnpm/scheduler@0.20.2/node_modules/scheduler/cjs/scheduler.development.js:468:12)
```

I notice that there has been a multitude of releases, all the way up to 6.1.0, but they're not on NPM. Is there somewhere else this package is released to?

**Comment by octylFractal** [comment]
Also, I think this is technically a duplicate of #22, differing react versions. It looks like the current `master` branch uses React 17, but as I mentioned, it's not released as far as I can tell.

**Comment by plantain-00** [comment]
It's a moporepo, the missing versions `eg: 6.0.0` only changes `select2-vue-component`'s code, so the uneffected `select2-react-component` doesn't have `6.0.0`.
I will release the master several hours later.

**Comment by plantain-00** [comment]
v6.1.1 released now.

**Comment by galanblancom** [comment]
I'm getting this message with React 18, any advice?

**Comment by maxcmoi89** [comment]
same here, I also get this error with react 18 and select2-react v6.1.1
